import {Box, Heading, SimpleGrid, Text} from "@chakra-ui/react";
import Head from "next/head";
import CourseBox from "../../../components/courseBox";
import Layout from "../../../components/layout";
import {useRouter} from "next/router";

export default function CoursePage({CourseData}) {
  const router = useRouter();
  const {id} = router.query;

  return (
    <Layout>
      <Box p={5}>
        <Head>
          <title>{id}</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/public/favicon.ico"/>
        </Head>
        <Heading size={"2xl"} mb={5}>{id}</Heading>
        <Text fontSize={"2xl"} color={"gray.500"} mb={5}>Pro zobrazení veškerého obsahu nezapomeňte se přihlásit do
          systému Plus4U.</Text>
        <SimpleGrid columns={2}>
          <CourseBox name={"Stránka předmětu (WEB)"} link={""}/>
          <CourseBox name={"Karta předmětu (Plus4U)"} link={"/"}/>
        </SimpleGrid>
      </Box>
    </Layout>
  );
}
