import {getCoursesData} from "../lib/courses";
import {Box, VStack} from "@chakra-ui/react";
import Head from "next/head";
import CourseBox from "../components/courseBox";
import Layout from "../components/layout";

export async function getStaticProps() {
  const coursesData = getCoursesData();
  // const res = await fetch('https://jsonplaceholder.typicode.com/users');
  // const usersData = await res.json();
  return {
    props: {
      Courses: coursesData
    }
  }
}

export default function Courses_list({Courses}) {
  return (
    <Layout>
      <Box p={5}>
        <Head>
          <title>Study programs</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <VStack spacing={4} align={"stretch"}>
          {
            Courses.coursesData.map(course => (<CourseBox name={course.name} link={course.link}/>))
          }
        </VStack>
      </Box>
    </Layout>
  );
}
