import Head from 'next/head'
import {Center, Heading, Grid, Box, Text, Image, AspectRatio, Flex, Link, GridItem} from "@chakra-ui/react";
import Layout, {siteTitle} from "../components/layout";
import CourseBox from "../components/courseBox";

export default function Home() {
    return (
        <Layout home>
            <Box p={5}>
                <Head>
                    <title>{siteTitle}</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <Heading size={"2xl"} mb={5}>Dostupné předměty</Heading>
                <Text fontSize={"2xl"} color={"gray.500"} mb={5}>Vyberte si jeden z předmětů pro zobrazení jeho detailů</Text>
                <Grid templateColumns="repeat(auto-fill, minmax(250px, 1fr))"
                      autoRows="minmax(250px, auto)" gap={6}>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                    <CourseBox/>
                </Grid>
            </Box>
        </Layout>
    )
}
