import Head from 'next/head'
import {Button, ButtonGroup, Center, Heading, Stack, Link, Image, Box} from "@chakra-ui/react";

export default function Home() {
    return (
        <Center bg={"purple.300"} minH={"100vh"}>
            <Head>
                <title>Main page - UUN Signpost</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Stack direction={"column"} align={"center"} spacing={"3rem"}>
                <Heading color={"whitesmoke"} size={"4xl"}>Welcome to the Unicorn University signpost page</Heading>
                <ButtonGroup spacing={"3rem"} size={"lg"} alignItems={"center"}>
                    <Button colorScheme={"purple"}>Enter</Button>
                    <Button colorScheme={"pink"}>About</Button>
                    {/*<Link href={"https://google.cz"} isExternal color={"white"}>Unicorn University</Link>*/}
                    <Button as={Link} colorScheme={"teal"} href={"https://google.cz"} isExternal>Unicorn University</Button>
                </ButtonGroup>
                <Box>
                    <Image src="https://picsum.photos/640/480?grayscale" borderRadius={"full"} objectFit={"cover"}
                           alt="Random Image"/>
                </Box>
            </Stack>
        </Center>
    )
}
