import Head from 'next/head'
import {Box, Center, Grid, GridItem, Heading, Link, Text, VStack} from "@chakra-ui/react";
import Layout, {siteTitle} from "../components/layout";
import CourseBox from "../components/courseBox";
import LinkNext from "next/link";

export default function Home() {
  return (
    <Layout home>
      <Box p={5}>
        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        {/*<Heading size={"2xl"} mb={5}>Předměty ZS v ak. roce 2021/2022.</Heading>*/}
        {/*<Text fontSize={"2xl"} color={"gray.500"} mb={5}>Vyberte si jeden z předmětů pro zobrazení jeho*/}
        {/*  detailů</Text>*/}
        {/*<Grid templateColumns="repeat(auto-fill, minmax(250px, 1fr))"*/}
        {/*      autoRows="minmax(250px, auto)" gap={6}>*/}
        {/*    {*/}
        {/*      Courses.coursesData.map(course => (<CourseBox name={course.name} link={course.link}/>))*/}
        {/*    }*/}
        {/*</Grid>*/}
        <Grid autoRows={"minmax(250px, auto)"} templateColumns={"repeat(3, 1fr)"} gap={6}>
          <GridItem colSpan={3}>
            <CourseBox name={"Předměty"} link={"/study_programs"} fontSize={"5rem"}/>
          </GridItem>
          <GridItem colSpan={1}>
            <CourseBox name={"Rozvrh předmětů"} link={"/"}/>
          </GridItem>
          <GridItem colSpan={1}>
            <Center border={"solid"} borderRadius={"xl"} bg={"gray.100"} w={"100%"} h={"100%"}>
              <VStack>
                {/*<LinkNext href={"/"} passHref>*/}
                {/*  <Link color={"black"} fontSize={"2rem"} isExternal={false}*/}
                {/*        noOfLines={5} placeContent={"center"}>Termíny zkoušek</Link>*/}
                {/*</LinkNext>*/}
                <Box>
                  <Heading fontSize={"lg"} color={"gray.500"}>Terminy zkousek</Heading>
                </Box>
                <Box>
                  <Text color={"gray.500"} fontSize={"sm"}>Budou zverejneny pozdeji v prubehu semestru</Text>
                </Box>
              </VStack>
            </Center>
          </GridItem>
          <GridItem colSpan={1}>
            <CourseBox name={"UUN Home page"} link={"https://unicornuniversity.net"} external/>
          </GridItem>
        </Grid>
      </Box>
    </Layout>
  )
}
