import {Box, VStack} from "@chakra-ui/react";
import Head from "next/head";
import Layout from "../components/layout";
import CourseBox from "../components/courseBox";

export default function StudyPrograms(){
  return(
    <Layout>
      <Box p={5}>
        <Head>
          <title>Study programs</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <VStack direction={"column"} spacing={4} align={"stretch"}>
          <CourseBox name={"Software Development"} link={"/study_years"}/>
          <CourseBox name={"Business management"} link={"/"}/>
        </VStack>
      </Box>
    </Layout>
  );
}
